CREATE TABLE "RELATORIOS"."LOGS_ZABBIX" 
   ("EVENT_ID" NUMBER NOT NULL ENABLE, 
	"CLIENTE" VARCHAR2(50 BYTE), 
	"HOST" VARCHAR2(200 BYTE), 
	"PROBLEMA" VARCHAR2(2000 BYTE), 
	"TRIGGERID" NUMBER(10,0), 
	"SEVERIDADE" VARCHAR2(20 BYTE), 
	"DATA" DATE, 
	"STATUS" VARCHAR2(50 BYTE), 
	"ID" NUMBER(4,0), 
	"TRIGGER_DESC" VARCHAR2(200 BYTE), 
	 CONSTRAINT "ID_PK" PRIMARY KEY ("ID"));
